### ISSUE TITLE
CSP: Refused to execute inline script.

### ISSUE THREAD

**Issue by klynton** [crazy-max/login-servers-enhanced#6]
Hey folks,

When trying to use the latest version of login-servers-enhanced along with the latest version of Adminer (4.7.3) in Firefox 69 and Safari 13.0.2 I can't switch between the 2 servers in the list because of this error:

`Refused to execute a script for an inline event handler because 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy.` The error comes from adminer line 61 which is this line:

```<table cellspacing="0"><tr><th>Server<td><input type="hidden" name="auth[driver]" value="server"><select name="auth[server]" onchange="switchServer();"><option value="127.0.0.1:3306" driver="server" selected>MariaDB</option><option value="127.0.0.1:5432" driver="pgsql">PostgreSQL</option></select><script type="text/javascript"  nonce="AREALNONCE">function switchServer() { var selectServer = document.getElementsByName("auth[server]")[0]; var driver = selectServer.options[selectServer.selectedIndex].getAttribute("driver"); document.getElementsByName("auth[driver]")[0].value = driver; }</script><tr><th>Username<td><input id="username" name="auth[username]" value=""><tr><th>Password<td><input type="password" name="auth[password]"></table><p><input type="submit" value="Login"><label><input type='checkbox' name='auth[permanent]' value='1'>Permanent login</label>```

Is there a workaround for this? I prefer the interface options on login-servers-enhanced compared to login-servers.

**Comment by crazy-max** [comment]
@klynton No issue for me with Adminer 4.7.4 and Firefox 69

Edit: Looks like an issue with Adminer 4.7.3: `Fix XSS if Adminer is accessible at URL /data:`
